import Head from "next/head"
import GalleryNavbar from "@/components/GalleryNavbar"
import GalleryHero from "@/components/GalleryHero"
import GalleryMain from "@/components/GalleryMain"
import ContactUs from "@/components/ContactUs"
import Footer from "@/components/Footer"
import { GalleryData } from "@/constants/GalleryData" 


export default function ContactUS() {
    return (
      <>
        <Head>
          <title>J&J Construction LLC</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='relative'>
           {/* Orange Background */}
          <div className='navOrange'/>
          <GalleryNavbar/>
          <GalleryHero/>
        </div>
        <GalleryMain cards={GalleryData}/>
        <ContactUs/>
        <Footer/>
      </>
    )
  }