import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import AboutUs from '@/components/AboutUs'
import Services from '@/components/Services'
import How from '@/components/How'
import MiniGallery from '@/components/MiniGallery'
import ContactUs from '@/components/ContactUs'
import Footer from '@/components/Footer'
import { ServiceData } from '@/constants/ServiceData'
import { GalleryData } from '@/constants/GalleryData'
import { HowData } from '@/constants/HowData'

export default function Home() {
  return (
    <>
      <Head>
        <title>J&J Construction LLC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='relative'>
         {/* Orange Background */}
        <div className='navOrange'/>
        <Navbar/>
        <Hero/>
      </div>
      <AboutUs/>
      <Services cards={ServiceData}/>
      <How cards={HowData}/>
      <MiniGallery/>
      <ContactUs/>
      <Footer/>
    </>
  )
}
