import Head from "next/head"
import Footer from "@/components/Footer"
import ServiceNavbar from "@/components/ServicesNavbar"
import SerivcesHero from "@/components/SerivcesHero"
import ServicesMain from "@/components/ServicesMain"
import ContactUs from "@/components/ContactUs"
import { ServiceData } from "@/constants/ServiceData"

export default function ContactUS() {
    return (
      <>
        <Head>
          <title>J&J Construction LLC</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='relative'>
           {/* Orange Background */}
          <div className='navOrange'/>
          <ServiceNavbar/>
          <SerivcesHero/>
        </div>
        <ServicesMain cards={ServiceData}/>
        <ContactUs/>
        <Footer/>
      </>
    )
  }