import Head from "next/head"
import Footer from "@/components/Footer"
import Hero2 from "@/components/Hero2"
import ServicesMain from "@/components/ServicesMain"
import ContactUs from "@/components/ContactUs"
import { ServiceData } from "@/constants/ServiceData"
import Navbar from "@/components/Navbar"
import servicesHeroImage from "public/Static/galleryHeroImage.webp"


export default function ContactUS() {
    return (
      <>
        <Head>
          <title>J&J Construction LLC</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className='relative'>
           {/* Orange Background */}
          <div className='navOrange'/>
          <Navbar 
          homeTab={false}
          serviceTab={true}
          galleryTab={false}
          contactUsTab={false}/>
          <Hero2 
            image = {servicesHeroImage}
            title = {0}
            text = {0}
            />
        </header>
        <ServicesMain cards={ServiceData}/>
        <ContactUs/>
        <Footer/>
      </>
    )
  }